theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: digitalnatives.mmibordeaux.com
  breadcrumb: 
    position: hero-end
  logo:
    header: "/assets/images/logo-blanc.svg"
    footer: "/assets/images/logo.svg"